# Site settings
author: Jonathan East
title: The Blog of Jonathan
header-img: img/home-bg.png
email: jonathan_east@ymail.com
copyright_name: Jonathan East
description: > # this means to ignore newlines until "baseurl:"
  a place to read about my revelations of becoming a Software Engineer
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  jeast00

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
